### ISSUE TITLE
review

### ISSUE THREAD

**Issue by masangana** [waqaskanju/to-do-list#2]
You should use ES6 syntaxe an foreach loop is better
 https://github.com/waqaskanju/to-do-list/blob/c9f3562627e2c0c0dd2904f6247992d5d1218ca8/src/modules/List.js#L77-L78

You should use ES6 to create your DOM and it isn't DRY
https://github.com/waqaskanju/to-do-list/blob/c9f3562627e2c0c0dd2904f6247992d5d1218ca8/src/index.js#L21-L59

You removed linter in your project
https://github.com/waqaskanju/to-do-list/blob/c9f3562627e2c0c0dd2904f6247992d5d1218ca8/.gitignore#L3-L5

Call to unused variable
https://github.com/waqaskanju/to-do-list/blob/d400d450884fd8325811ca35e0a95858fe1d1750/src/modules/List.js#L28

**Comment by waqaskanju** [comment]
thanks for you suggestions.
